apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dw593ww5q-python 
  janus-idp.io/tekton: dw593ww5q-python
  backstage.io/kubernetes-id: dw593ww5q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dw593ww5q-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml